[WIP] Triplet eval
HPI-MachineIntelligence-MetaLearning/multi-building-detector pull request #11
Opened 2018-01-29 22:06 UTC by shorschig

Reports average distances per class when the evaluator is called.

Also saves scatter plots of the feature vectors if configured.

[WIP] because I'm in the process of cleanup, but this doesn't take long.

2018-01-30 00:33 UTC, nstrelow reviewed
Tested with GPU and test_trigger=20. (and 10),
Does not finish, seems to take a lot of time calulcation the evaluation. Need to test on the server.

2018-01-30 00:33 UTC, nstrelow commented on config/gpu_default.yml
> +model_module: multibuildingdetector.models.SSDTriplet
Thank you for putting those in!!!!

2018-01-30 17:10 UTC, fapaul requested changes
@shorschig  Currently it is not working on the server see the stacktrace below 
```
Traceback (most recent call last):
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/site-packages/chainer/training/extensions/evaluator.py", line 137, in __call__
    result = self.evaluate()
  File "/home/msws18place2/multi-building-detector/multibuildingdetector/evaluators/tripletevaluator.py", line 80, in evaluate
    avg_dist = mean(distances)
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/statistics.py", line 330, in mean
    raise StatisticsError('mean requires at least one data point')
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/msws18place2/multi-building-detector/multibuildingdetector/__main__.py", line 141, in <module>
    main()
  File "/home/msws18place2/multi-building-detector/multibuildingdetector/__main__.py", line 137, in main
    run(**config)
  File "/home/msws18place2/multi-building-detector/multibuildingdetector/__main__.py", line 126, in run
    trainer.run()
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/msws18place2/.local/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/site-packages/chainer/training/extensions/evaluator.py", line 137, in __call__
    result = self.evaluate()
  File "/home/msws18place2/multi-building-detector/multibuildingdetector/evaluators/tripletevaluator.py", line 80, in evaluate
    avg_dist = mean(distances)
  File "/home/msws18place2/anaconda3/envs/multi-building-detector-gpu/lib/python3.5/statistics.py", line 330, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point
```

2018-01-30 23:19 UTC, fapaul requested changes
Unfortunately, I can't refactor most of it currently because both GPUs are used and I don't want to break stuff. Some things need further explanation @shorschig. So far so good 👍

2018-01-30 23:19 UTC, mockingbird2 commented on multibuildingdetector/evaluators/tripletevaluator.py
> +    def evaluate(self):
Can you split up this method? It seems to be pretty big.

2018-01-30 23:19 UTC, mockingbird2 commented on multibuildingdetector/evaluators/tripletevaluator.py
> +            if label != 0:
Please catch the zero label case explicit like 
```python
if label == 0:
    continue
```

2018-01-30 23:19 UTC, mockingbird2 commented on multibuildingdetector/evaluators/tripletevaluator.py
> +    def plot_roc_curves(self, label_groups):
This method is also pretty large and does a lot.

2018-01-30 23:19 UTC, mockingbird2 commented on multibuildingdetector/evaluators/tripletevaluator.py
> +        for labels, confs in zip(gt_labels, mb_confs):
I don't really understand this loop since both variables `labels, conf` are both not used.

2018-01-30 23:19 UTC, mockingbird2 commented on multibuildingdetector/evaluators/tripletevaluator.py
> +    def filter_overlapping_bboxs(self, mb_boxs, mb_confs, gt_labels):
Maybe we can refactor the `SSDTripleloss` to make this method static callable so we don't have to add it here.

2018-01-30 23:19 UTC, mockingbird2 commented on multibuildingdetector/evaluators/tripletevaluator.py
> +    def center_point(self, points):
Method could be static

2018-01-30 23:19 UTC, mockingbird2 commented on multibuildingdetector/evaluators/tripletevaluator.py
> +    def convert_label_groups(self, label_groups):
The method could be static too. Can you explain why this method is needed?

2018-03-21 13:14 UTC, fapaul approved these changes

2018-03-21 13:14 UTC, merged